version: '3.7'

services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedback-kiosk-prod
    restart: unless-stopped
    ports:
      - '5050:5050'
    command: npm run dev
